const SUPABASE_URL = "https://nseeeapxviahenzuqkil.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZWVlYXB4dmlhaGVuenVxa2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3MDY5MzQsImV4cCI6MjEwMjI4MjkzNH0.JNROm5b11QR8I1AlN4ICXCe5vd8lF1C_HgBw5sGozVk";
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);